### ISSUE TITLE
Hardware revision request: Mounting holes & supercap

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/SparkFun_Real_Time_Clock_Module_RV-8803#3]
A quick note to suggest if this board ever sees a hardware revision or is replaced by the RV-3032, mounting holes should definitely be included.

Having worked with this RTC since it was released, I can report it can be very awkward to use, as it can't easily be connected/mounted to other Qwiic boards using standoffs. While it can be soldered onto a protoboard, it generally needs to be soldered at an angle or upside down to ensure the coin cell holder doesn't cause a short.

IMO, the design of the RV-1805, including the use of a supercap instead of a coin-cell, is preferable.

Cheers,
Adam

**Comment by adamgarbo** [comment]
An update a couple of years later that I still believe the lack of mounting holes are a major weakness of this board. It would pair super well with the [Datalogger IoT 9DoF](https://www.sparkfun.com/products/20594), if only could be mounted directly!

**Comment by brhoff720** [comment]
Hi Adam,

Just so you know, I agree mounting holes would be great.  It has been noted
as a revision change.  It's in the backlog, but may be a very long time
before design is updated.

**Comment by adamgarbo** [comment]
Hi Bryan, 

I've just been tidying up my GitHub issues that have been open for a very long time. Thanks for the note.

Cheers,
Adam
